src/Entity/Topic.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TopicRepository")
 */
class Topic
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    public $name;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Post", mappedBy="topic", orphanRemoval=true)
     * @ORM\OrderBy({"upvotes" = "Desc"})
     */
    private $posts;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $Description;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="topics")
     */
    private $author;

    public function __construct()
    {
        $this->posts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return (string)$this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection|post[]
     */
    public function getPosts(): Collection
    {
        return $this->posts;
    }

    public function addPost(post $post): self
    {
        if (!$this->posts->contains($post)) {
            $this->posts[] = $post;
            $post->setTopic($this);
        }

        return $this;
    }

    public function removePost(post $post): self
    {
        if ($this->posts->contains($post)) {
            $this->posts->removeElement($post);
            // set the owning side to null (unless already changed)
            if ($post->getTopic() === $this) {
                $post->setTopic(null);
            }
        }

        return $this;
    }
    public function __toString()
    {
        try
        {
            return (string) $this->name;
        }
        catch (Exception $exception)
        {
            return '';
        }
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getAuthorsCount($posts)
    {
        $authors = array();
        foreach($posts as $post){
            // Count every poster
            $author = $post->getAuthor();
            if(!in_array($author,$authors)){
                $authors[] = $author;
            }

            // Count every commenter
            foreach($post->getComments() as $comment){
                $author = $comment->getAuthor();
                if(!in_array($author,$authors)){
                    $authors[] = $author;
                }

                //Count every comment liker
                foreach($comment->getLikedBy() as $user_){
                    if(!in_array($user_,$authors)){
                        $authors[] = $user_;
                    }
                }
            }

            //Count every post liker
            foreach($post->getLikedBy() as $user){
                if(!in_array($user,$authors)){
                    $authors[] = $user;
                }
            }
        }
        return $authors;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use FOS\UserBundle\Model\User as BaseUser;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class User extends BaseUser
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Post", inversedBy="users")
     */
    private $posts;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $registered;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Post", mappedBy="author")
     */
    private $createdposts;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="author")
     */
    private $comments;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Post", mappedBy="likedBy")
     */
    private $liked_posts;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Comment", mappedBy="likedBy")
     */
    private $liked_comments;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Topic", mappedBy="author")
     */
    private $topics;


    public function __construct()
    {
        parent::__construct();
        $this->posts = new ArrayCollection();
        $this->createdposts = new ArrayCollection();
        $this->addRole("ROLE_USER");
        $this->comments = new ArrayCollection();
        $this->liked_posts = new ArrayCollection();
        $this->liked_comments = new ArrayCollection();
        $this->topics = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return Collection|Post[]
     */
    public function getPosts(): Collection
    {
        return $this->posts;
    }

    public function addPost(Post $post): self
    {
        if (!$this->posts->contains($post)) {
            $this->posts[] = $post;
        }

        return $this;
    }

    public function removePost(Post $post): self
    {
        if ($this->posts->contains($post)) {
            $this->posts->removeElement($post);
        }

        return $this;
    }

    public function getRegistered(): ?\DateTimeInterface
    {
        return $this->registered;
    }

    public function setRegistered(\DateTimeInterface $registered): self
    {
        $this->registered = $registered;

        return $this;
    }

    /**
     * @return Collection|Post[]
     */
    public function getCreatedposts(): Collection
    {
        return $this->createdposts;
    }

    public function addCreatedpost(Post $createdpost): self
    {
        if (!$this->createdposts->contains($createdpost)) {
            $this->createdposts[] = $createdpost;
            $createdpost->setAuthor($this);
        }

        return $this;
    }

    public function removeCreatedpost(Post $createdpost): self
    {
        if ($this->createdposts->contains($createdpost)) {
            $this->createdposts->removeElement($createdpost);
            // set the owning side to null (unless already changed)
            if ($createdpost->getAuthor() === $this) {
                $createdpost->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAuthor($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getAuthor() === $this) {
                $comment->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Post[]
     */
    public function getLikedPosts(): Collection
    {
        return $this->liked_posts;
    }

    public function getLikedPostsCount()
    {
        return $this->liked_posts->count;
    }


    public function addLikedPost(Post $likedPost): self
    {
        if (!$this->liked_posts->contains($likedPost)) {
            $this->liked_posts[] = $likedPost;
            $likedPost->addLikedBy($this);
        }

        return $this;
    }

    public function removeLikedPost(Post $likedPost): self
    {
        if ($this->liked_posts->contains($likedPost)) {
            $this->liked_posts->removeElement($likedPost);
            $likedPost->removeLikedBy($this);
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getLikedComments(): Collection
    {
        return $this->liked_comments;
    }

    public function addLikedComment(Comment $likedComment): self
    {
        if (!$this->liked_comments->contains($likedComment)) {
            $this->liked_comments[] = $likedComment;
            $likedComment->addLikedBy($this);
        }

        return $this;
    }

    public function removeLikedComment(Comment $likedComment): self
    {
        if ($this->liked_comments->contains($likedComment)) {
            $this->liked_comments->removeElement($likedComment);
            $likedComment->removeLikedBy($this);
        }

        return $this;
    }

    /**
     * @return Collection|Topic[]
     */
    public function getTopics(): Collection
    {
        return $this->topics;
    }

    public function addTopic(Topic $topic): self
    {
        if (!$this->topics->contains($topic)) {
            $this->topics[] = $topic;
            $topic->setAuthor($this);
        }

        return $this;
    }

    public function removeTopic(Topic $topic): self
    {
        if ($this->topics->contains($topic)) {
            $this->topics->removeElement($topic);
            // set the owning side to null (unless already changed)
            if ($topic->getAuthor() === $this) {
                $topic->setAuthor(null);
            }
        }

        return $this;
    }


}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('username')
            ->add('usernameCanonical')
            ->add('email')
            ->add('emailCanonical')
            ->add('enabled')
            ->add('salt')
            ->add('password')
            ->add('lastLogin')
            ->add('confirmationToken')
            ->add('passwordRequestedAt')
            ->add('roles')
            ->add('registered')
            ->add('posts')
            ->add('liked_posts')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\User1Type;
use App\Repository\UserRepository;
use App\Repository\TopicRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("{_locale}/user")
 */
class UserController extends AbstractController
{
    /**
     * @Route("/", name="user_index", methods={"GET"})
     */
    public function index(UserRepository $userRepository): Response
    {
        return $this->render('user/index.html.twig', [
            'users' => $userRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="user_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $user = new User();
        $form = $this->createForm(User1Type::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirectToRoute('user_index');
        }

        return $this->render('user/new.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="user_show", methods={"GET"})
     */
    public function show(User $user,TopicRepository $topicRepository): Response
    {
        return $this->render('user/show.html.twig', [
            'user' => $user,'topics' => $topicRepository->findAll(),
        ]);
    }

    /**
     * @Route("/{id}/edit", name="user_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, User $user): Response
    {
        $form = $this->createForm(User1Type::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('user_index', [
                'id' => $user->getId(),
            ]);
        }

        return $this->render('user/edit.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="user_delete", methods={"DELETE"})
     */
    public function delete(Request $request, User $user): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($user);
            $entityManager->flush();
        }

        return $this->redirectToRoute('user_index');
    }
}

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('user_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn">Delete</button>
</form>

templates/user/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit User{% endblock %}

{% block body %}
    <h1>Edit User</h1>

    {{ include('user/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('user_index') }}">back to list</a>

    {{ include('user/_delete_form.html.twig') }}
{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}User index{% endblock %}

{% block body %}
    <h1>User index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Username</th>
                <th>UsernameCanonical</th>
                <th>Email</th>
                <th>EmailCanonical</th>
                <th>Enabled</th>
                <th>Salt</th>
                <th>Password</th>
                <th>LastLogin</th>
                <th>ConfirmationToken</th>
                <th>PasswordRequestedAt</th>
                <th>Roles</th>
                <th>Id</th>
                <th>Registered</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td>{{ user.username }}</td>
                <td>{{ user.usernameCanonical }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.emailCanonical }}</td>
                <td>{{ user.enabled ? 'Yes' : 'No' }}</td>
                <td>{{ user.salt }}</td>
                <td>{{ user.password }}</td>
                <td>{{ user.lastLogin ? user.lastLogin|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ user.confirmationToken }}</td>
                <td>{{ user.passwordRequestedAt ? user.passwordRequestedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ user.roles ? user.roles|join(', ') : '' }}</td>
                <td>{{ user.id }}</td>
                <td>{{ user.registered ? user.registered|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('user_show', {'id': user.id}) }}">show</a>
                    <a href="{{ path('user_edit', {'id': user.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="14">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('user_new') }}">Create new</a>
{% endblock %}

templates/user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New User{% endblock %}

{% block body %}
    <h1>Create new User</h1>

    {{ include('user/_form.html.twig') }}

    <a href="{{ path('user_index') }}">back to list</a>
{% endblock %}

templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{user.username}}{% endblock %}
{% block navbar %}
 <div id="topic-nav" class="text-center">
        <a href="{{ path('index') }}" class="nav-link"><i class="fas fa-home"></i></a>
        {% for topic in topics| sortbyfield('name') %}
            <a href="{{ path('topic_show', {'id': topic.id}) }}" class="nav-link">{{ topic.name }}</a>         
        {% endfor %}
</div>
<div id="login-nav" class="text-center">
<div class="row">
<a href="/lt/" class="nav-link col ml-3">
<span class="flag-icon flag-icon-lt"></span>
</a>
<a href="/en/" class="nav-link col mr-3">
<span class="flag-icon flag-icon-gb"></span>
</a></div>
    {% if is_granted('ROLE_USER')%}
<a href="{{ path('user_show',{'id' : app.user.id}) }}" class="nav-link">{{app.user.username|capitalize}}</a>
                    <a href="{{ path('post_index') }}" class="nav-link"><div class="button">{% trans %}My posts{% endtrans %} <span class="button__badge">{{app.user.createdPosts|length}}</span></div></a>


                    <a href="{{ path('topic_index') }}" class="nav-link"><div class="button">{% trans %}My topics{% endtrans %} <span class="button__badge">{{app.user.topics|length}}</span></div></a>


                    <a href="{{ path('fos_user_security_logout') }}" class="nav-link btn-danger text-white">{% trans %}Logout{% endtrans %}</a>

            {% else %}

<a href="{{ path('fos_user_security_login') }}" class="nav-link"><span class="glyphicon glyphicon-log-in"></span> {% trans %}Login{% endtrans %}</a>

                <a href="{{ path('fos_user_registration_register') }}" class="nav-link btn-danger text-white">{% trans %}Register{% endtrans %}</a>

            {% endif %}
</div>
<button onclick="window.location.href='{{ path('index') }}'" id="back-to-list" title="Go to list"><i class="fas fa-chevron-left"></i></button> 
{% endblock %}

{% block body %}


    {# User details #}
    <div class="logo_index"><h1 class="text-center text-white" style="margin-top: 75px;font-size:70px;">{{ user.username }}</h1></div>
        <div class="container" style="position:absolute;top:185px;left: 375px;margin-top:30px;margin-bottom:30px;">
            <div class="container" style="background-color: var(--second_color); margin-bottom:30px;-webkit-border-radius: 10px;border-radius: 10px;">
                <p>{% trans %}Last login{% endtrans %}: {{user.lastLogin|time_diff|trans|raw ? : 'just now'}}</p>
            </div>
    {# Posts #}

        <div class="container" style="background-color: var(--second_color); margin-bottom:30px;-webkit-border-radius: 10px;border-radius: 10px;">
            <br><h1 class="text-center">//{% trans %}My posts{% endtrans %}</h1><br>
            {% if user.createdposts|length > 0 %}

        <table class="table table-borderless frontpage" id="seperator">

            {% for post in user.createdposts | sortbyfield('upvotes')|reverse%} 
                    <tr>
                    <section>
                    <td class="align-middle" style="width: 8%;">
                    {{ post.likedBy|length }}
                    {% if app.user in post.likedBy %} 
                    <img src="{{ asset('build/images/Heart.png') }}" id="unlike" onclick="window.location.href='{{ path('default_post_like', {'id': post.id}) }}'" width="25px" height="25px" />
                    {% else %} 
                    <img src="{{ asset('build/images/Heart.png') }}" id="like" onclick="window.location.href='{{ path('default_post_like', {'id': post.id}) }}'" width="25px" height="25px"/>
                    {% endif %}
                    </td>
                    <td onclick="window.location.href='{{ path('post_show', {'id': post.id}) }}'" class="frontpage" id="post" style="cursor: pointer;">
                    <article class="post">
                    <p class="post-meta">{{ post.Title }} * <span>{% trans %}Posted by{% endtrans %}</span> <a href="{{ path('user_show', {'id': post.author.id}) }}">{{ post.author }}</a> * {{post.Date|time_diff|trans|raw ? : 'just now'}}</p>
                    <p>{{ post.Data|length > 240 ? post.Data|raw|slice(0, 240)|raw : post.Data|raw }} {% trans %}... Click to read more{% endtrans %}</a></p> 
                    </article>
                    </td>
                    </section>
                    </tr>
            {% endfor %}
            {% else %}
            <tr>
            <td class="align-middle" style="width: 8%;"><td>
            <td class="frontpage" id="post" style="cursor: pointer;">
            <p><br>{% trans %}No post created yet, press add, to add new post{% endtrans %}<br>gif..</p>
            </td>
            </tr>
            {% endif %}


        </table></div>
    

    {# Topics #}

        <div class="container" style="background-color: var(--second_color); margin-bottom:30px;-webkit-border-radius: 10px;border-radius: 10px;">
            <br><h1 class="text-center">//{% trans %}My topics{% endtrans %}</h1><br>
            {% if user.topics|length > 0 %}

        <table class="table table-borderless frontpage" id="seperator">

            {% for topic in user.topics | sortbyfield('name')|reverse%} 
                    <tr>
                    <section>
                    <td onclick="window.location.href='{{ path('topic_show', {'id': topic.id}) }}'" class="frontpage" id="post" style="cursor: pointer;">
                    <article class="post">
                    <p class="post-meta">{{ topic.name }}</p>
                    <p>{{ topic.description|length > 240 ? topic.description|raw|slice(0, 240)|raw : topic.description|raw }}{% trans %}... Click to read more{% endtrans %}</a></p> 
                    </article>
                    </td>
                    </section>
                    </tr>
            {% endfor %}
            {% else %}
            <tr>
            <td class="align-middle" style="width: 8%;"><td>
            <td class="frontpage" id="post" style="cursor: pointer;">
            <p><br>{% trans %}No topics created yet, press add, to add new topic{% endtrans %}<br>gif..</p><br>
            </td>
            </tr>
            {% endif %}


        </table></div>

    {# Comments #}

    <div class="container" style="background-color:var(--second_color); margin-bottom:30px;-webkit-border-radius: 10px;border-radius: 10px;">
<br><h1 class="text-center">//{% trans %}My comments{% endtrans %}</h1><br>
    <table class="table table-borderless frontpage" id="seperator">
    <tbody>
    {% for comm in user.comments| sortbyfield('likedCount')|reverse %}
    <tr>
    <td class="align-middle" style="width: 8%"> {{ comm.likedBy|length }} 
        {% if app.user in comm.likedBy %}
            <img src="{{ asset('build/images/Heart.png') }}" onclick="window.location.href='{{ path('comment_like', {'id': comm.id}) }}'" width="25px" height="25px" id="unlike" />
        {% else %} 
            <img src="{{ asset('build/images/Heart.png') }}" onclick="window.location.href='{{ path('comment_like', {'id': comm.id}) }}'" width="25px" height="25px" id="like"/>
        {% endif %}
     </td>
    <td class="comment">
        <p class="post-meta"><b>{{ comm.author }}</b> *
        {{comm.Date|time_diff|trans|raw ? : 'just now'}}</p>
        <p>{{ comm.comment|nl2br }}</p>
        {# TODO ADD RESPOND#}
        {% if comm.response|length > 0 %}
        <p>
        {{dump(comm)}}
        {% for resp in comm.response %}
        <p>{{ resp.comment|nl2br }}</p>
        {% endfor %}
        </p>
        {% endif %}
</td></tr>
    {% endfor %}
            
        </tbody>
    </table>
    </div>
    </div>

{% endblock %}